version: '3.7'

services:
  web:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
      - app_static_volume:/app/static
      - app_media_volume:/app/files
    ports:
      - "8000:8000"
    networks:
      - app_network
      - nginx_network
    depends_on:
      - db
      - redis
  db:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app_network
    env_file:
      - ./.env.db
  redis:
    container_name: redisdb
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  postgres_data:
    external: true
  app_static_volume:
    external: true
  app_media_volume:
    external: true
networks:
  app_network:
    external: true
  nginx_network:
    external: true