version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - app_static_volume:/app/static
      - app_media_volume:/app/files
    networks:
      - nginx_network

volumes:
  app_static_volume:
    external: true
  app_media_volume:
    external: true
networks:
  nginx_network:
    external: true